### ISSUE TITLE
Review from team DreamJobs

### ISSUE THREAD

**Issue by Naveenksaragadam** [INFO-526-FA24/project-2-stat-squad#10]
I really love how you've simplified an overly complex process, making it much easier for the audience to understand. The poster is well put together, and the theme works really well. 

There are a few suggestions that could make it even better. Since the poster will be static, instead of displaying the live version, consider creating a static image that clearly highlights the starting and ending points of the process. Additionally, including a brief write-up for each optimizer, outlining their pros, cons, and when to choose each one, would add significant value for the user. Providing some context while presenting would also be really beneficial. 

Great job overall, and good luck!

**Comment by ksomeswara** [comment]
Fixed the Issue based on the feedback
