### ISSUE TITLE
Poster review from Visual voyagers

### ISSUE THREAD

**Issue by gr98765** [INFO-526-FA24/project-2-stat-squad#11]
Hello team Stat-squad,

Strength:The poster effectively presents an engaging topic on gradient descent optimizers, with a well-organized layout and clear workflow.

Suggestions: -The 3D plots are visually engaging, but adding a short summary or annotations for each optimizer would help clarify their functionality.
-Improving the color choices in the final plot would provide a clearer idea of the conclusion drawn from all the optimizers and make the visualization more accessible.

overall, great work.

**Comment by ksomeswara** [comment]
Fixed the Issue based on the feedback
