### ISSUE TITLE
Review by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-stat-squad#13]
Hello Team Stat Squad

Strengths:
1) The use of animated plots with gganimate adds a dynamic and engaging element to the presentation.
2) The animations effectively showcase trends and patterns in the synthetic data.

Weaknesses:
1) The graphs are not self-explanatory, requiring additional context or explanation.
2) Limited annotations or labels reduce the accessibility and immediate understanding of the visualizations.

**Comment by ksomeswara** [comment]
Fixed the Issue based on the feedback
