### ISSUE TITLE
Team DataVizionaries review - MOCK iShowcase

### ISSUE THREAD

**Issue by h-akston** [INFO-526-FA24/project-2-stat-squad#4]
The big strength of this work its educational value. Neural Networks optimizers are an extremely complex topic, and making it any clearer with one single poster and 3 minutes of conversation is a great achievement!

One weakness, and it is only a weakness for a poster, is that the work relies on animations to convey the ideas. The team will have to make some changes to convey those same ideas with static images.

Overall, great job tackling smth this complex!

**Comment by PrasanthGubbala** [comment]
Thanks for the feedback! We’ll focus on converting the animations into static images to ensure the ideas are clearly conveyed on the poster. Overall, we appreciate the recognition of the educational value of the work and will aim to keep that clarity intact in the final presentation.
