### ISSUE TITLE
Team Pixels and Patterns

### ISSUE THREAD

**Issue by sindhugoshika** [INFO-526-FA24/project-2-stat-squad#5]
Hello Team Stat Squad,

Your visualizations are fantastic and clearly reflect your deep interest and knowledge in deep learning. However, I’m concerned that, as we are limited to posters, the potential of your GIF visualizations might not be fully showcased.

Additionally, I feel it would be more impactful if you focused on solving a specific problem through your visualizations rather than explaining different types of optimizers. This approach could create a more cohesive narrative for your poster.

That said, I’m eagerly looking forward to seeing how you present on iShowcase day. Wishing you all the best!

Team Pixels and Patterns

**Comment by PrasanthGubbala** [comment]
Thanks for the feedback! We’ll focus on refining the GIF visualizations for the poster and shift the narrative towards solving a specific problem, rather than explaining various optimizers, to create a more cohesive presentation. Looking forward to showcasing the final work on iShowcase day!
