### ISSUE TITLE
Review from Epidata

### ISSUE THREAD

**Issue by YitianQian777** [INFO-526-FA24/project-2-stat-squad#6]
Topic: Deep learning optimizer

Strength: The poster is eye-catching, dynamic and clear.

Weakness: For the poster, you could briefly introduce the concept/background of deep learning first. For the plots, you could introduce what the starting and ending points are. And perhaps add some more key points for the plots.

**Comment by PrasanthGubbala** [comment]
Thanks for the feedback! The necessary improvements (brief background on deep learning, clarification of starting/ending points in plots, and adding key points for better context) will be addressed to enhance the poster and presentation.
