### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-stat-squad#9]
Strengths:
The visualizations on the poster are well-crafted and aesthetically pleasing, showcasing a strong attention to detail. The spacing on the poster is thoughtfully utilized, ensuring a clean and organized layout that enhances readability and visual appeal.

Weaknesses:
Some plots are challenging to interpret, potentially due to their complexity or lack of explanatory elements. Additionally, the color choices for certain plots make it difficult to distinguish the plotted points clearly, which can hinder the audience's ability to fully understand the data. Adjustments to simplify the plots and refine the color palette could significantly improve clarity and overall effectiveness.

**Comment by ksomeswara** [comment]
Fixed the Issue based on the feedback
